name: Build to ACR deploy to App Service using Managed Identity

on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

env:
    IMAGE_NAME: htmx-image
    LOCATION: eastus
    AZURE_WEBAPP_NAME: htmxappsvc

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # checkout the repo
        - uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Login to ACR via OIDC
          run: az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
                     
        # - name: Login to ACR
        #   uses: docker/login-action@v3
        #   with:
        #     registry: ${{ secrets.REGISTRY_LOGIN_SERVER 

        - name: Build image
          run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        - name: Push image
          run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    deploy:
      runs-on: ubuntu-latest
      
      needs: build

      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: logout
        run: |
            az logout
